### ISSUE TITLE
Meetup #3 Checklist

### ISSUE THREAD

**Issue by IRus** [BelarusKUG/Community#11]
## Подготовка:
- [x] Прослушивание @madhead на Emap Kotlin Tech Talk 
- [x] Форма регистрации
- [x] Написание анонса
- [x] Анонс запаблишить на [bkug.by](https://bkug.by/), [events.dev.by](https://events.dev.by/) и [@BelarusKUG](https://twitter.com/BelarusKUG)
- [x] Репост и рассылка от партнеров: Space, JavaDay
- [x] Сделать рассылку анонса (Mailchimp)
- [x] Дизайн стикера с вышиванкой
- [x] Печать стикеров с вышиванкой и по мотивам ЗВ

Стикеры обычно заказываем у [sorokdva.by](http://sorokdva.by/), email: ap@sorokdva.by

Анонс можно расылать за неделю, и в день митапа. Должен содержать программу и карту проезда.

## Пред Митап
- [x] Фотосъемка (Есть)
- [x] Видеозапись (Уточнить у Space)
- [x] Вступительная речь (Руслан)
- [x] Кофе-пауза (Уточнить у Space)

Видеозапись - напомнить площадке что требуется видеозаписать, обсудить шаблон (то какая будет компоновка видео)

Вступительная речь - если требуется, заранее составить, дабы ничего не забыть.

Кофе-пауза - договориться о кофе-паузе

## Митап

- [x] Разложить стикеры
- [x] Выставить роллап
- [x] Объявление спикеров
- [x] Собрать у спикеров материалы (код, презентации)

## Пост Митап

- [x] Сделать опрос
- [x] Написать отчет на сайт, зарепостить везде
- [x] Ссылку на отчет и опрос отправить в рассылку на зарегистрированных участников

**Comment by madhead** [comment]
```
### Сергей Крюков

Spring 5 - предстоящий релиз популярного фреймворка Spring, запланированный к выходу уже к этому лету.
В этой версии мы увидим новый, реактивный, подход к написанию приложений, а Kotlin-разработчиков может заинтересовать поддержка их любимого языка.

Сергей расскажет о поддержке Kotlin в Spring 5, а именно о:

 - Плагине kotlin-spring
 - Расширениях для GenericApplicationContext
 - Расширениях для RestTemplate
 - Встроенной поддержке nullable-типов
 - Применении Kotlin в MVC-шаблонах
 - Расширениях для Reactor
 - Kotlin DSL для WebFlux
```
